baseURL                = "https://innnnnk.github.io/"
locale                 = "zh-cn"
title                  = "遇玄的方外之地"
defaultContentLanguage = "zh-cn"
hasCJKLanguage         = true
theme                  = "stack"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"


