[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"
    weight     = 1

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 2

[[main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search/"
    weight     = 3

[[main]]
    identifier = "random-thoughts"
    name       = "💭 碎碎念"
    url        = "/random-thoughts/"
    weight     = 4

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/innnnnk"
