mainSections   = ["post"]
rssFullContent = true
SortBy         = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = "2006-01-02"
    lastUpdated = "2006-01-02"

[sidebar]
    compact = false
    avatar  = ""

[article]
    headingAnchor = false
    math          = false
    toc           = true
    readingTime   = true

    [article.list]
        showTags = false

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page     = [{ type = "recent-articles" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

[imageProcessing]
    autoOrient = false

    [imageProcessing.content]
        widths  = [800, 1600, 2400]
        enabled = true

    [imageProcessing.thumbnail]
        enabled = true

[cookies]
    enabled = false

[comments]
    enabled = false
